# Generated by Django 4.2.3 on 2023-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=15)),
                ('placa', models.CharField(max_length=7)),
                ('renavam', models.CharField(max_length=20)),
                ('capacidade', models.IntegerField()),
                ('combustivel', models.CharField(max_length=45)),
                ('potencia', models.CharField(max_length=45)),
                ('cor', models.CharField(max_length=12)),
                ('ano', models.CharField(max_length=4)),
                ('disponivel', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cambio', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatico')], max_length=1)),
                ('cover', models.ImageField(upload_to='core/covers/%Y/%m/%d/')),
            ],
        ),
    ]
