# Generated by Django 4.2.2 on 2023-07-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_veiculo_capacidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('C', 'Carro'), ('M', 'Moto')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cambio',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatico')], max_length=1),
        ),
    ]
