# Generated by Django 4.2.2 on 2023-07-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_veiculo_tipo_alter_veiculo_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('C', 'Carro'), ('M', 'Moto')], max_length=1),
        ),
    ]
