# Generated by Django 4.2.2 on 2023-07-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_veiculo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ar_condicionado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cd_dvd',
            field=models.BooleanField(default=True),
        ),
    ]
